FROM golang:latest as build

WORKDIR /go/src/
RUN git clone https://github.com/istio/istio.git

RUN cd /go/src/istio/samples/health-check && \
  CGO_ENABLED=0 GOOS=linux go build server.go

FROM registry.access.redhat.com/ubi8/ubi:latest as release
RUN yum update -y && yum install -y ca-certificates

COPY --from=build /go/src/istio/samples/health-check/server ./server

CMD ["./server"]