--- 
arch: ppc64le
distro: bionic
os: linux

env:
  global:
    TRAVIS_DEBUG_MODE=true

jobs: 
  include: 
    - 
      if: "branch = master AND type = pull_request"
      script: 
        - "echo Sample"
