#!/bin/bash
set -x
[[ -s ${APP_ROOT}/container_env ]] && source ${APP_ROOT}/container_env

echo "== Writing encryption key =="
cat > /var/www/miq/vmdb/certs/v2_key << KEY
---
:algorithm: aes-256-cbc
:key: ${ENCRYPTION_KEY}
KEY

echo "${GUID}" > ${APP_ROOT}/GUID

export DISABLE_MIQ_WORKER_HEARTBEAT=1

[[ -n $EMS_IDS ]] && WORKER_OPTIONS="--ems-id=${EMS_IDS} "

exec bin/rails r ${APP_ROOT}/lib/workers/bin/run_single_worker.rb ${WORKER_OPTIONS}${WORKER_CLASS_NAME}
