# ----------------------------------------------------------------------------
#
# Package             : ant-tar-patched
# Source Repo         : https://github.com/Zimbra/ant-tar-patched
# Travis Job Link     : https://travis-ci.com/github/nageshlop/ant-tar-patched/builds/213606541
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
dist: xenial
language: java
arch:
  - amd64
  - ppc64le
before_install:
  - sudo apt-get install ant
script: 
  - ant -f ${TRAVIS_BUILD_DIR}/build.xml
