# ----------------------------------------------------------------------------
# Package             : aproba
# Source Repo         : https://github.com/iarna/aproba
# Travis Job Link     : https://travis-ci.com/github/sanjaymsh/aproba/builds/219128502
# Created travis.yml  : No
# Maintainer          : Sanjay Mishra <snjkmr32@gmail.com>
# Script License      : Apache License, Version 2 or later
# ----------------------------------------------------------------------------
 
language: node_js
sudo: false
arch:
  - amd64
  - ppc64le
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
matrix:
  allow_failures:
     - node_js: 6
     - node_js: 4
