# ----------------------------------------------------------------------------
# #
# # Package             : balanced-match 
# # Source Repo         : https://github.com/juliangruber/balanced-match 
# # Travis Job Link     : https://travis-ci.com/github/sanjaymsh/balanced-match/builds 
# # Created travis.yml  : No
# # Maintainer          : Sanjay Mishra <snjkmr32@gmail.com> 
# #
# # Script License      : Apache License, Version 2 or later
# #
# # -------------------------------------------------------------------------

language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

arch:
  - amd64
  - ppc64le

matrix:
    exclude:
         - node_js: "0.12"
           arch: ppc64le

script:
   - npm install
   - npm test
