# ----------------------------------------------------------------------------
#
# Package             : chest
# Source Repo         : https://github.com/blaze/chest
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/chest/jobs/471998061
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
arch:
    - amd64
    - ppc64le
# Removed unsupported python versions 2.6 and 3.3
python:
    - "2.7"
    - "3.4"

env:
    - PEP8_IGNORE=""

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coverage  # Removed unsupported option --use-mirrors
    - pip install pep8 # Removed unsupported option --use-mirrors

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - coverage run --source=chest $(which nosetests)
                   --with-doctest
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing --fail-under=100 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pep8 --ignore=$PEP8_IGNORE --exclude=conf.py -r --show-source . ; fi

# load coverage status to https://coveralls.io
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls ; coveralls ; fi  # Removed unsupported option --use-mirrors

notifications:
  email: false
