# ----------------------------------------------------------------------------
#
# Package             : cmd-shim
# Source Repo         : https://github.com/ForbesLindesay/cmd-shim.git
# Travis Job Link     : https://travis-ci.com/github/santosh653/cmd-shim
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: node_js

node_js:
  - node
  - 12
  - 10
os:
  - linux
  

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false
