# ----------------------------------------------------------------------------
#
# Package             : commons-lang
# Source Repo         : https://github.com/apache/commons-lang
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/commons-lang/builds/218061689
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

cache:
  directories:
    - $HOME/.m2

arch:
  - amd64
  - ppc64le

jdk:
  - openjdk8
  - openjdk11
  - openjdk15
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

before_install:
# For power support architecture ppc64le
# Manual maven install fixes the issue of Maven version allowed range 3.5.0. or above
# sed command fixes the error javadoc command and environment variable JAVA_HOME setup
 - |
   if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     mkdir -p /opt/maven;
     curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven;
     export MAVEN_HOME=/opt/maven
     export PATH=${MAVEN_HOME}/bin:${PATH}
     sed '/maven.compiler.source/ i <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>' pom.xml > tmp && mv tmp pom.xml;
   fi

script:
  - mvn -V --no-transfer-progress
 
after_success:
  - mvn -V --no-transfer-progress clean test jacoco:report coveralls:report -Ptravis-jacoco javadoc:javadoc -Ddoclint=all
