# ----------------------------------------------------------------------------
#
# Package             : dill
# Source Repo         : https://github.com/uqfoundation/dill
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/dill/builds/213467461
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

dist: trusty
language: python

matrix:
    include:
        - python: '2.7'
          env:
            - COVERAGE="true"

        - python: '3.6'
          dist: xenial
          env:
            - COVERAGE="true"
            - NUMPY="true"

        - python: '3.7'
          dist: xenial
          env:

        - python: '3.8'
          dist: xenial
          env:

        - python: '3.9'
          dist: xenial
          env:

        - python: '3.10-dev'
          dist: xenial
          env:

        - python: 'nightly'
          dist: xenial
          env:

        - python: 'pypy'
          env:

        - python: 'pypy3'
          dist: xenial
          env:
 
    # Power jobs
        - python: '2.7'
          dist: xenial
          env:
            - COVERAGE="true"
          arch: ppc64le

        - python: '3.6.7'  # Specifying the minor version so that assert in tests/test_detect.py is handled
          dist: xenial
          env:
            - COVERAGE="true"
            - NUMPY="true"
          arch: ppc64le

        - python: '3.7'
          dist: xenial
          env:
          arch: ppc64le

        - python: '3.8'
          dist: xenial
          env:
          arch: ppc64le

        - python: '3.9'
          dist: xenial
          env:
          arch: ppc64le

        - python: '3.10-dev'
          dist: xenial
          env:
          arch: ppc64le

        - python: 'nightly'
          dist: xenial
          env:
          arch: ppc64le

    allow_failures:
        - python: '3.10-dev'
        - python: 'nightly'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $NUMPY == "true" ]]; then pip install numpy; fi

install:
    - python setup.py build && python setup.py install

script:
    - for test in tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
