# ----------------------------------------------------------------------------
#
# Package             : error-prone
# Source Repo         : https://github.com/google/error-prone
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/error-prone
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk-ea

matrix:
  include:
    - jdk: openjdk10
      before_install:
        # https://github.com/travis-ci/travis-ci/issues/9368#issuecomment-395354755
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk15
      script:
        # default Maven command
        - mvn test -B
        # also test Javadoc generation
        - mvn -P '!examples' javadoc:aggregate
    # Power job
    # For ppc64le build annotation module
    - arch: ppc64le
      jdk: openjdk11
      install: skip
      script:
       - cd annotation
       - mvn test -B
       # Set JAVA_HOME for javadoc
       - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-ppc64el
       - mvn -P '!examples' javadoc:aggregate
    - arch: ppc64le
      jdk: openjdk8
      dist: xenial
      install: skip
      script:
       - cd annotation
       - mvn test -B
       # Set JAVA_HOME for javadoc
       - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
       - mvn -P '!examples' javadoc:aggregate
    - arch: ppc64le
      jdk: openjdk12
      dist: xenial
      install: skip
      script:
       - cd annotation
       - mvn test -B
       # Set JAVA_HOME for javadoc
       - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-12-hotspot-ppc64el
       - mvn -P '!examples' javadoc:aggregate
    - arch: ppc64le
      jdk: openjdk14
      dist: xenial
      install: skip
      script:
       - cd annotation
       - mvn test -B
       # Set JAVA_HOME for javadoc
       - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot-ppc64el
       - mvn -P '!examples' javadoc:aggregate

  allow_failures:
    - jdk: openjdk-ea

# see https://github.com/travis-ci/travis-ci/issues/8408
before_install:
- unset _JAVA_OPTIONS

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.m2

notifications:
  #email: error-prone-team@google.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/74d33a22fbfb1942920e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

# Store encrypted credentials for gh-pages and sonatype:
# travis encrypt -r google/error-prone GH_TOKEN=<github access token>
# travis encrypt -r google/error-prone CI_DEPLOY_USERNAME=<sonatype username>
# travis encrypt -r google/error-prone CI_DEPLOY_PASSWORD=<sonatype password>

env:
  global:
    - secure: "kM6uLpPkYz/i5FTMAh0yUyhLrmJFDr643u49i9FHreg+L5n+DYUilbRPOfHhN802Wd9Pb1yGkFxbumuzo+ZjTjHmyjH5w5hsRvRrPVX3FRnMN5SMCnE95nBZJOyMrYHYnko+IXsENqqfPjTe5d/fUsMcwYcIPuqssaO+lvTv0Yw="
    - secure: "VTl3ljwGf0KPbX5wW1+MgQuLwpfSppph/STiyUOQkISO5jDwBAfnvcBymn/oLESwQeLZ/D+GZtL/sooG2Kf6v8Fdn6Q6VhwfSxgLDJUME+A4rOBBnDExhpUz+OT0XugWHfQ/sYRaDRk1/c1axt3XB/cxlzPNIJKlzDoPZpfDyGM="
    - secure: "FHXaeHYXmdGNYZLuSbAE7c5xmIhUT8/VzpnlkVmDgCPXgOGY7RzCpF4MVPIDm7f63bx/qZSu+d008gFHTI98UQLHMACjD1wuahk+0vqXVG1W3WwruqilTriYjW1gUkwa5zv5AaApq0dd5CO7li1DpNPgqOrU50ddJlb0BZ6wv1Q="

after_success:
  - util/publish-snapshot-on-commit.sh

# https://docs.travis-ci.com/user/web-ui/#build-pushed-branches
# safelist
branches:
  only:
  - master
