# ----------------------------------------------------------------------------
#
# Package             : escape-html-library
# Source Repo         : https://github.com/component/escape-html
# Travis Job Link     : https://travis-ci.com/github/santosh653/escape-html
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.16"
  - "7.10"
  - "8.15"
  - "9.11"
  - "10.15"
  - "11.6"
#Excluding unsupported node_js versions on power
jobs:
 exclude:
  - node_js: "0.6"
    arch: ppc64le
  - node_js: "0.8"
    arch: ppc64le
  - node_js: "0.10"
    arch: ppc64le
  - node_js: "0.12"
    arch: ppc64le
  - node_js: "1.8"
    arch: ppc64le
  - node_js: "2.5"
    arch: ppc64le
  - node_js: "3.3"
    arch: ppc64le

sudo: false
dist: precise
cache:
  directories:
    - node_modules
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Remove all non-test dependencies
  - |
    # Remove bench dependencies
    npm rm --save-dev benchmark
    npm rm --save-dev beautify-benchmark
  # Setup Node.js version-specific dependencies
  - |
    # eslint for linting
    # - remove on Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
        grep -E '^eslint(-|$)' | \
        xargs npm rm --save-dev
    fi
  - |
    # mocha for testing
    # - use 1.x for Node.js < 0.8
    # - use 2.x for Node.js < 0.10
    # - use 3.x for Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq 0 && "$(cut -d. -f2 <<< "$TRAVIS_NODE_VERSION")" -lt 8 ]]; then
      npm install --save-dev mocha@1.21.5
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq 0 && "$(cut -d. -f2 <<< "$TRAVIS_NODE_VERSION")" -lt 10 ]]; then
      npm install --save-dev mocha@2.5.3
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm install --save-dev mocha@3.5.3
    fi
  - |
    # nyc for coverage
    # - remove for Node.js < 0.10
    # - use 10.x for Node.js < 4
    # - use 11.x for Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq 0 && "$(cut -d. -f2 <<< "$TRAVIS_NODE_VERSION")" -lt 10 ]]; then
      npm rm --save-dev nyc
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 4 ]]; then
      npm install --save-dev nyc@10.3.2
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm install --save-dev nyc@11.9.0
    fi
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  - |
    # Run test script, depending on nyc install
    if npm -ps ls nyc | grep -q nyc; then
      npm run-script test-cov
    else
      npm test
    fi
  - |
    # Run linting, depending on eslint install
    if npm -ps ls eslint | grep -q eslint; then
      npm run-script lint
    fi
after_script:
  - |
    # Upload coverage to coveralls if exists
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
