# ----------------------------------------------------------------------------
#
# Package             : eventing
# Source Repo         : https://github.com/knative/eventing
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/eventing/builds/219740600
# Created travis.yml  : Yes
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: go

go:
 - 1.16.x
 - tip

arch:
 - amd64
 - ppc64le

script: 
 - go test -v ./pkg/...  -tags=e2e
