 ----------------------------------------------------------------------------
#
# Package             : expressions
# Source Repo         : https://github.com/DataBrewery/expressions
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/expressions
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
   
arch:
   - amd64
   - ppc64le   

install:
   - pip install e .
   - python setup.py install

script: 
   - py.test
