# ----------------------------------------------------------------------------
#
# Package             : heapdict
# Source Repo         : https://github.com/DanielStutzbach/heapdict
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/heapdict/builds/213473839
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
   
arch:
   - amd64
   - ppc64le   

script: 
   - python setup.py install
   - python test_heap.py
