# ----------------------------------------------------------------------------
#
# Package             : history.js
# Source Repo         : https://github.com/browserstate/history.js/
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/history.js/builds/223261744
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---
language: node_js

node_js:
   - 10
   - lts/*
   
allow_failures:
   - node
   
arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 
