# ----------------------------------------------------------------------------
#
# Package             : is-stream
# Source Repo         : https://github.com/sindresorhus/is-stream
# Travis Job Link     : https://travis-ci.com/github/santosh653/is-stream
# Created travis.yml  : Yes
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
arch: 
  - amd64
  - ppc4le
language: node_js
node_js: node
script:
  - npm install
