# ----------------------------------------------------------------------------
#
# Package             : jetty-reactive-httpclient 
# Source Repo         : https://github.com/jetty-project/jetty-reactive-httpclient
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/jetty-reactive-httpclient/builds/230581268
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: java

jdk:
  - openjdk8
  - openjdk11
  
dist: bionic

arch:
  - amd64
  - ppc64le

script:
     - mvn test
