# ----------------------------------------------------------------------------
#
# Package             : Jolokia
# Source Repo         : https://github.com/rhuss/jolokia
# Travis Job Link     : https://travis-ci.com/github/santosh653/jolokia
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: java
dist: xenial
before_install:
  - echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts
after_script:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_JDK_VERSION == openjdk8 ]] && [[ $TRAVIS_BRANCH == master ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}"
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_JDK_VERSION == openjdk8 ]] && [[ $TRAVIS_BRANCH == '2.0' ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.branch=2.0"
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
