# ----------------------------------------------------------------------------
#
# Package             : js-file-download
# Source Repo         : https://github.com/kennethjiang/js-file-download.git
# Travis Job Link     : https://travis-ci.com/github/santosh653/js-file-download
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - "8.12.0"
