# ----------------------------------------------------------------------------
#
# Package             : kiali
# Source Repo         : https://github.com/kiali/kiali.git
# Travis Job Link     : https://travis-ci.com/github/BalavvaMirji/kiali/builds/233647985
# Created travis.yml  : No
# Maintainer          : Balavva Mirji <Balavva.Mirji@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: go
dist: bionic
arch:
  - ppc64le
go:
  - 1.16.x
script:
  - make build test
  - go test -v ./...