# ----------------------------------------------------------------------------
#
# Package             : log4j-jsonevent-layout
# Source Repo         : https://github.com/logstash/log4j-jsonevent-layout
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/log4j-jsonevent-layout/builds/213271044
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

jdk:
  - openjdk9
  - openjdk11

arch:
  - amd64
  - ppc64le

before_script:
  - sudo apt update -y
  - sudo apt-get install maven
