# ----------------------------------------------------------------------------
#
# Package             : manageiq
# Source Repo         : https://github.com/ManageIQ/manageiq
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/manageiq/builds/218210546
# Created travis.yml  : No
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

---
language: ruby
rvm:
- 2.5.8
- 2.6.6
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  - PARALLEL_TEST_PROCESSORS=2
  matrix:
  - TEST_SUITE=vmdb PARALLEL=true
  - TEST_SUITE=brakeman
matrix:
  fast_finish: true
  jobs:
  - sudo: required
    group: edge
    virt: lxd
    dist: bionic
    arch: arm64-graviton2
    rvm: 2.6.6
    env:
    - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
    - RUBY_GC_HEAP_INIT_SLOTS=600000
    - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
    - PARALLEL_TEST_PROCESSORS=2
    - TEST_SUITE=vmdb PARALLEL=true
  # Power jobs
  - sudo: required
    dist: bionic
    arch: ppc64le
    rvm: 2.6.6
    env:
    - TEST_SUITE=vmdb PARALLEL=true
  - sudo: required
    dist: bionic
    arch: ppc64le
    rvm: 2.6.6
    env:
    - TEST_SUITE=brakeman
addons:
  postgresql: '10'
before_install: 
    - | 
      if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then
        sudo apt update;
        sudo apt install -y libpq-dev; # To fix a missing header file issue
      fi
    - source ${TRAVIS_BUILD_DIR}/bin/ci/before_install.sh
before_script: source ${TRAVIS_BUILD_DIR}/bin/ci/before_script.sh
after_failure: source ${TRAVIS_BUILD_DIR}/bin/ci/after_failure.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7af45001fe6b7a4039f2
    on_success: change
    on_failure: always
    on_start: never
