# ----------------------------------------------------------------------------
#
# Package             : nbsetuptools
# Source Repo         : https://github.com/Anaconda-Platform/nbsetuptools
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/nbsetuptools
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

arch:
   - amd64
   - ppc64le

python:
   - 3.8

script:
   - python setup.py install
   - pip install jupyter_core
   - pip install notebook
   # test_enable has an open issue https://github.com/Anaconda-Platform/nbsetuptools/issues/12
   - pytest -k "not test_enable"
