# ----------------------------------------------------------------------------
#
# Package             : nestedSortable
# Source Repo         : https://github.com/ilikenwf/nestedSortable
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/nestedSortable
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: node_js

node_js:
    - 10
    - node
    - lts/*

arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 

jobs:
  allow_failures:
  - node_js: node
