# ----------------------------------------------------------------------------
#
# Package             : node-red
# Source Repo         : https://github.com/node-red/node-red.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/node-red/builds/212689675
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
sudo: false
addons:
  chrome: stable
language: node_js
matrix:
  include:
    - node_js: "14"
      script:
        - ./node_modules/.bin/grunt && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
        #    - scripts/install-ui-test-dependencies.sh && grunt test-ui
      before_script:
        - npm install -g coveralls
    - node_js: "12"
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "10"
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "8"
      script:
        - ./node_modules/.bin/grunt no-coverage
#Added power jobs
    - node_js: "14"
      arch: ppc64le
      script:
        - ./node_modules/.bin/grunt && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
        #    - scripts/install-ui-test-dependencies.sh && grunt test-ui
      before_script:
        - npm install -g coveralls
    - node_js: "12"
      arch: ppc64le
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "10"
      arch: ppc64le
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "8"
      arch: ppc64le
      script:
        - ./node_modules/.bin/grunt no-coverage
