# ----------------------------------------------------------------------------
#
# Package             : ordereddict
# Source Repo         : https://github.com/gururajrkatti/ordereddict
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/ordereddict/builds/218556692
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

arch:
  - amd64
  - ppc64le

python: 2.7

dist: bionic

install:
  - python setup.py build
  - sudo python setup.py install

script:
  - nosetests
