# ----------------------------------------------------------------------------
#
# Package             : parse5
# Source Repo         : https://github.com/inikulin/parse5
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/parse5/builds/212285038
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js
sudo: false
node_js:
  - stable
arch:
  - amd64
  - ppc64le
