# ----------------------------------------------------------------------------
#
# Package             : petlx
# Source Repo         : https://github.com/petl-developers/petlx
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/petlx/builds/218929122
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

python: 
   # Doesn't work with python3
   # Fails with "decoding str is not supported"
   - 2.7  
   
arch:
   - amd64
   - ppc64le   

install:
   - easy_install pip
   - pip install setuptools pytest nose
   - pip install -r test_requirements.txt
   - python setup.py install

script: 
   - pytest
