# ----------------------------------------------------------------------------
#
# Package             : pyclaw
# Source Repo         : https://github.com/clawpack/pyclaw
# Travis Job Link     : https://travis-ci.com/github/asellappen/pyclaw/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

os: linux
dist: xenial
arch:
    - amd64
    - ppc64le
env:
  matrix:
    - TEST_PACKAGE="pyclaw"
    - TEST_PACKAGE="petclaw"
    - TEST_PACKAGE="forestclaw"

python:
  - 3.6.10


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - sudo apt-get install pv liblapack-dev
  - sudo apt-get install libhdf5-serial-dev
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update clawutil visclaw riemann
  - rm -rf pyclaw
  - ln -s ../ pyclaw

install:

  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - sudo apt-get install openmpi-bin
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install -c conda-forge mpich mpi4py
  - conda install matplotlib nose coverage
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then 
      conda install -c clawpack hdf5-parallel h5py-parallel ;
    fi
  - conda install -c conda-forge petsc4py
  - conda install -c conda-forge scipy
  - conda install -c conda-forge vtk
  - conda install -c conda-forge python-coveralls
  - conda install -c conda-forge pytables
  - python setup.py install

script:
  # TEST_PACKAGE  "pyclaw" &  "petclaw" are failing in amd64 for the last few branch with same issues,now failing for both arch, and have raised the issue to community   
  # https://github.com/clawpack/pyclaw/issues/666
  - cd pyclaw
  - bash ./run_tests_on_travis.sh

after_success:
  - coveralls

notifications:
  email: false
