# ----------------------------------------------------------------------------
#
# Package             : python-ftfy
# Source Repo         : https://github.com/LuminosoInsight/python-ftfy
# Travis Job Link     : https://travis-ci.com/github/nageshlop/python-ftfy/builds/221604954
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
language: python

dist: xenial 

arch: 
  - amd64
  - ppc64le

python:
  - 3.8

script:
  - python setup.py install
  - pytest 
