# ----------------------------------------------------------------------------
#
# Package             : python-dropbox
# Source Repo         : https://github.com/enginoid/python-dropbox
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/python-dropbox
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

arch:
  - amd64
  - ppc64le

python: 2.7

dist: bionic

install:
  - pip install nose
  - python setup.py build
  - python setup.py install

script:
  - nosetests
