# ----------------------------------------------------------------------------
#
# Package             : pythonfutures
# Source Repo         : https://github.com/agronholm/pythonfutures
# Travis Job Link     : https://travis-ci.com/github/santosh653/pythonfutures
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
sudo: false

stages:
  - name: test
  - name: deploy to pypi
    if: type = push AND tag =~ ^\d+\.\d+\.\d+

jobs:
 include:
  - env: TOXENV=pypy
    python: pypy
    arch: amd64
  - env: TOXENV=py26
    dist: trusty
    python: "2.6"
    arch: amd64
  - env: TOXENV=py27
    arch: amd64
  #Python Versions pypy & 2.6 are not supported on power, so not including them for power
  - env: TOXENV=py27
    arch: ppc64le

  - stage: deploy to pypi
    install: skip
    script: skip
    deploy:
        provider: pypi
        user: agronholm
        password:
          secure: Dp2GLO5NK0cAV5uVSxq1s1Ux3IaJM/GYPskR8Nja9uTsktNmAhsPVDH+/w7a79G7ngyAoFv+GmDNXmAUOd6B3FrpnF9Lk4KIwSQ+agGQsdmQ5NrTVF33AXNMQiqLFd1nTq7g/or4qzUiDST9YgT3o6oIJwmGQRtTx4ZmIXSiGyMgQvxX27eMalLmA/FovgilxSkS3oEvhNTMgXI/E5CUgsFQC1rKcl+rzqfDv2kZoatrc0qrxMPeuDkNxZx9qb8gjstjcVJCjLZPZaIL2nSY6iQ2NdeKzLX2yDSXJn1yO+BX+1xlglxMYK+WUUQZvqExhWKm1sCsExSuvmF62FS0OLjLoUDNxKEQlSqS/fRZGAbDFkM4vxAWl89PF3MAFV12OES/HKA7cjbQcvPmAVC/88G3SSB5NxgsK/jOjhYh3scZtG/o6Mk5MB02ZqQdT7pNtMWK3B3XKUutK+zXWU975+1QG7sy/9O2qQpgIEkOGdIfZyNu3tS9k+1GmBKp1Va/e8VpfcAuHiV0U4zLnv8JJoCGWsdA69hkmue2oQ8CDIM8DBBQ1xJckCHa8ulvOoX5nCoVeumL23M60rKKSppqmcEC56vgfj1SMLpIYo75X4d5G3Y9ZcGFEWJoW0PdRZXmqoZAPqA30JPKIRV/oKr6FEJ1SFwiL8w9Lh1aHi7R06c=
        distributions: sdist bdist_wheel
        on:
          tags: true

python: "2.7"

install: pip install tox

script: tox
