# ----------------------------------------------------------------------------
#
# Package             : querystring
# Source Repo         : https://github.com/get/querystring.git
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/querystring/builds/212809914
# Created travis.yml  : Yes
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js

node_js:
  - 14
  - 15

arch:
  - amd64
  - ppc64le

script:
  - npm audit fix --force
  - npm install
