# ----------------------------------------------------------------------------
#
# Package             : quicklz
# Source Repo         : https://github.com/robottwo/quicklz
# Travis Job Link     : https://travis-ci.com/github/ddeka2910/quicklz/builds/218579185
# Created travis.yml  : Yes
# Maintainer          : Debabrata Deka <ddeka2910@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: true

dist: xenial
arch:
  - amd64
  - ppc64le
language: c++

env:
  global:
    - PREFIX=/usr/local
    
script:
  - ./configure -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX 
  - sudo make install
