# ----------------------------------------------------------------------------
#
# Package             : react-grid-layout
# Source Repo         : https://github.com/STRML/react-grid-layout.git
# Travis Job Link     : https://travis-ci.com/github/santosh653/react-grid-layout
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - 10
  - 12
  - "lts/*"
script:
  - make build test
cache: yarn
