# ----------------------------------------------------------------------------
#
# Package             : sample-travis-job 
# Source Repo         : https://github.com/Siddhesh-Ghadi/sample-travis-job.git
# Travis Job Link     : https://travis-ci.com/github/Siddhesh-Ghadi/sample-travis-job/builds/210384845
# Created travis.yml  : Yes
# Maintainer          : Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
  
dist: bionic

script:
  - echo "SAMPLE TRAVIS JOB"
