# ----------------------------------------------------------------------------
#
# Package             : sassc-ruby
# Source Repo         : https://github.com/sass/sassc-ruby/
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/sassc-ruby/builds/215002287
# Created travis.yml  : No
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "bundle exec rake test"
arch:
  - amd64
  - ppc64le
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7.0
  - truffleruby
jobs:
 exclude:
  - arch: ppc64le
    rvm: truffleruby
notifications:
  email: false
