# ----------------------------------------------------------------------------
#
# Package             : setimmediate
# Source Repo         : https://github.com/YuzuJS/setImmediate.git
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/setImmediate/builds/215036747
# Created travis.yml  : Yes
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: node_js

node_js:
  - 12
  - 14
  
arch:
  - amd64
  - ppc64le

before_script:
  - npm install
