os: linux
dist: focal
arch: ppc64le
language: shell

branches:
  only:
  - travis-currency-poc


services:
    - docker

before_install:
    - sudo apt install -y jq; jq --version

jobs:
  include:
    - stage: Build info
      name: Get Build info details
      script:
        - chmod +x ./script/read_buildinfo.sh;bash ./script/read_buildinfo.sh
      workspaces:
        create:
          name: build_cache
          paths:
            - variable.sh

    - stage: Build package
      name: Build script run
      workspaces:
        use: build_cache
      script: 
        - source variable.sh
        - if [ ${VALIDATE_BUILD_SCRIPT} == true ]; then chmod +x ./script/build_package.sh; bash -x ./script/build_package.sh; fi


    - stage: Build docker image
      name: Docker build
      before_script:
        - chmod +x ./script/read_buildinfo.sh;bash ./script/read_buildinfo.sh
        - source variable.sh
      script: 
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x ./script/build_docker.sh; bash -x ./script/build_docker.sh; fi
        - echo "printing docker images"
        - docker images
      workspaces:
        create:
          name: docker_image_tar
          paths:
            - image.tar
        

    - stage: Run Scanner
      name: Run trivy scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/trivy_scan.sh;bash ./script/trivy_scan.sh; fi
        
    - name: Run syft scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/syft_scan.sh;bash ./script/syft_scan.sh; fi

    - name: Run grype scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/grype_scan.sh;bash ./script/grype_scan.sh; fi
 
