# ----------------------------------------------------------------------------
#
# Package             : zjsonpatch
# Source Repo         : https://github.com/flipkart-incubator/zjsonpatch
# Travis Job Link     : https://travis-ci.com/github/gururajrkatti/zjsonpatch/builds/218319516
# Created travis.yml  : Yes
# Maintainer          : Gururaj R Katti <Gururaj.Katti@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

arch:
  - amd64
  - ppc64le

jdk: openjdk8

install: skip

before_script:
  - |
    if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
      export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-ppc64el; # mvn fails without this setting
    fi


script:
  - mvn integration-test
