# ----------------------------------------------------------------------------
#
# Package	: appsody/stacks/incubator/nodejs-loopback
# Version	: latest (0.2.2)
# Source repo	: https://github.com/appsody/stacks/tree/master/incubator/nodejs-loopback
# Tested on	: rhel_7.6
# Script License: Apache License, Version 2.0
# Maintainer	: Vrushali Inamdar <vrushali.inamdar@ibm.com>
#
# Disclaimer: This script has been tested in root mode on given
# ==========  platform using the mentioned version of the package.
#             It may not work as expected with newer versions of the
#             package and/or distribution. In such case, please
#             contact "Maintainer" of this script.
#
# ----------------------------------------------------------------------------

#!/bin/bash

# ----------------------------------------------------------------------------
# Prerequisites:
#
# Docker Version 18.06.1-ce or later is installed and running
#
# This stack is dependent on images generated by appsody/nodejs stack. The dockerfiles committed with this script, assume that the "nodejs" appsody stack 
# images are available under "dev.local" appsody repository.
#
# appsody binary version 0.5.8 or greater is available in path 
# ----------------------------------------------------------------------------

export APPSODY_STACKS_VERSION=""

wrkdir=`pwd`

# NOTE :: Make sure that above 2 commands have successfully generated the docker images

# get the source code for stacks repo
git clone https://github.com/appsody/stacks.git
cd stacks

if [ "$APPSODY_STACKS_VERSION" == "" ]
then
   echo "No specific version specified. Using latest ..."
else
   echo "Building the specified version $APPSODY_STACKS_VERSION"
   git checkout ${APPSODY_STACKS_VERSION}
fi

cd ./incubator/nodejs-loopback

# NOTE :: Replace image/Dockerfile-stack with 'Dockerfile-stack' and image/project/Dockerfile with 'Dockerfile'
# present in the current directory.
cp -f $wrkdir/Dockerfile-stack image/Dockerfile-stack
cp -f $wrkdir/Dockerfile image/project/Dockerfile

appsody stack validate 

echo "Appsody stack - nodejs-loopback is validated !"