os: linux
dist: focal
arch: ppc64le
language: shell

branches:
  only:
  - travis-currency-poc

env:
  global:
    - PACKAGE_NAME="d3-array"
    - VERSION="v3.2.3"

services:
    - docker

before_install:
    - sudo apt install -y jq; jq --version

jobs:
  include:
    - stage: Build info
      name: Get Build info details
      script:
        # This script will read build_info.sh and create variable.sh file with export statement, so that we can source this file latest stages to use variables.
        - chmod +x ./script/read_buildinfo.sh;bash -x ./script/read_buildinfo.sh
      workspaces:
        create:
          #To share file creating workspace
          name: build_cache
          paths:
            - variable.sh

    - stage: Build
      name: Build script run
      script:
        - source variable.sh
        - ls -ltr
        - if [ ${VALIDATE_BUILD_SCRIPT} == true ]; then chmod +x ./script/build_package.sh; bash -x ./script/build_package.sh; fi
        - pwd
        - ls -ltr
        - cd /home/tester
        - ls -ltr   
      workspaces:
        create:
          name: package_build_folder_cache
          paths:
            - .
        use: build_cache


    - stage: Build docker image
      name: Docker build
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x ./script/build_docker.sh; bash -x ./script/build_docker.sh;echo "printing docker images"; docker images; fi
      workspaces:
        create:
          name: docker_image_tar
          paths:
            - image.tar
        use: package_build_folder_cache


    - stage: Run Scanner
      name: Run trivy scan
      workspaces:
        use:
          - package_build_folder_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/trivy_scan.sh;bash ./script/trivy_scan.sh; fi

    - name: Run syft scan
      workspaces:
        use:
          - package_build_folder_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/syft_scan.sh;bash ./script/syft_scan.sh; fi

    - name: Run grype scan
      workspaces:
        use:
          - package_build_folder_cache
          - docker_image_tar
      script:
        - source variable.sh
        - if [ ${BUILD_DOCKER} == true ]; then docker load -i "$HOME/build/$TRAVIS_REPO_SLUG/image.tar"; chmod +x ./script/grype_scan.sh;bash ./script/grype_scan.sh; fi
