FROM registry.access.redhat.com/ubi8/ubi
RUN yum install vim java-1.8.0-openjdk-devel maven git -y
env JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
env JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk/jre
CMD ["bash"]
