# Minimum requirements for the build system to execute.
[build-system]
requires = [
    "setuptools",
    "wheel",
]

# Set build backend to setuptools
build-backend = "setuptools.build_meta"

# Project name and version
[project]
name = "thriftcpp"
version = "{PACKAGE_VERSION}"

# One line description
description = "Provides thrift-cpp for C++ packaging"

# License declaration for PEP 621 / SBOM compliance
license = { text = "Apache-2.0" }

# Classifiers to improve package discoverability
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: C++",
  "License :: OSI Approved :: Apache Software License",
]

# Project URLs
[project.urls]
homepage = "https://github.com/apache/thrift"
upstream = "https://github.com/apache/thrift"

# Find package files in local folder
[tool.setuptools.packages.find]
namespaces = true
where = ["local"]

# Package data to include headers, libs, and cmake/pkgconfig files
[tool.setuptools.package-data]
thriftcpp = ["*/*", "*/*/*", "*/*/*/*"]

[tool.distutils.bdist_wheel]
plat-name = "linux_ppc64le"  # Explicitly set the platform tag
universal = false  # Disable universal wheel (forces platform-specific build)
