[build-system]
# Minimum requirements for the build system to execute.
# Do not include sys, subprocess and os as they are default packages
requires = [
    "setuptools",
    "wheel",
]
# Set build backend to setuptools
build-backend = "setuptools.build_meta"

# Project name and version
[project]
name = "openblas"
version = "v0.3.33"
# One line description
description = "OpenBLAS: An optimized BLAS library"
# Classifiers to improve package discoverability
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: C++",
  "License :: OSI Approved :: BSD License",
]

# Project URLs
[project.urls]
homepage = "https://github.com/xianyi/OpenBLAS"
upstream = "https://github.com/xianyi/OpenBLAS"

# Find package files in local folder, this is needed as we are not following standard directory structure of setuptools
[tool.setuptools.packages.find]
# scanning for namespace packages is true by default in pyproject.toml, so
# you do NOT need to include the following line.
namespaces = true
where = ["local"]

# Package data to add binaries in wheel, this is needed as they are not .py files
[tool.setuptools.package-data]
openblas = ["lib/*", "include/*", "lib/pkgconfig/*", "lib/cmake/openblas/*"]

[tool.distutils.bdist_wheel]
plat-name = "linux_ppc64le"
universal = false            # Disable universal wheel (forces platform-specific build)
