#!/bin/sh
#
# Copyright 2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -eu

# This downloads and extracts the indicated version alpine-minirootfs into the current directory.

full_version=${1?full_version ex 3.18.2}
version=$(echo "${full_version}" | sed -En "s/^([0-9]+\.[0-9]+)\.[0-9]+$/\1/p")
patch=$(echo "${full_version}" | cut -f3 -d.)

# Normalize arch to what's available
arch=$(uname -m)
case ${arch} in
  amd64* )
    arch=x86_64
    ;;
  x86_64* )
    arch=x86_64
    ;;
  ppc64le* )
    arch=ppc64le
    ;;
  arm64* )
    arch=aarch64
    ;;
  aarch64* )
    arch=aarch64
    ;;
  s390x* )
    arch=s390x
    ;;
  * )
    >&2 echo "Unsupported arch: ${arch}"
    exit 1;
esac

echo "Extracting alpine-minirootfs v${full_version} for ${arch} architecture"
wget -qO- https://dl-cdn.alpinelinux.org/alpine/v${version}/releases/${arch}/alpine-minirootfs-${version}.${patch}-${arch}.tar.gz| tar xz